webtalk_init -webtalk_dir E:/Users/jccx1/Documents/TUDelft_projects_root/AI/Lab-2/MultiLayerPerceptron_NN/MultiLayerPerceptron_NN.sim/sim_1/behav/xsim/xsim.dir/first_layer_testbench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jun  9 15:58:47 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2ad55a32-0a38-458d-8a7a-2c95e2dc9f86" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e76e05d07e494408ac9025c9f6c3a88e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2808 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.20_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "253956_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3210006976 -regid "" -xml E:/Users/jccx1/Documents/TUDelft_projects_root/AI/Lab-2/MultiLayerPerceptron_NN/MultiLayerPerceptron_NN.sim/sim_1/behav/xsim/xsim.dir/first_layer_testbench_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/Users/jccx1/Documents/TUDelft_projects_root/AI/Lab-2/MultiLayerPerceptron_NN/MultiLayerPerceptron_NN.sim/sim_1/behav/xsim/xsim.dir/first_layer_testbench_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/Users/jccx1/Documents/TUDelft_projects_root/AI/Lab-2/MultiLayerPerceptron_NN/MultiLayerPerceptron_NN.sim/sim_1/behav/xsim/xsim.dir/first_layer_testbench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
